### PR TITLE
Add Support For Multiple Rooms

### PR DESCRIPTION
**Pull request by leefaus**
@geekgonecrazy @Sing-Li 

- added simplified setup through npm link (docs needed)
- [added support for multiple rooms](https://github.com/RocketChat/hubot-rocketchat/issues/16)

Can I get some :eyes: on these changes?

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Looks good.  Some reason doesn't work through docker.  

Couple of little things:
ROCKETCHAT_ROOM probably should just have GENERAL in it.  Since that other rooms id will be different on other servers. 
ROCKETCHAT_URL probably should be localhost by default

**Comment by Sing-Li** [comment]
Going to try it here, in my 'lab environment',  on docker as well. reporting back shortly.

**Comment by geekgonecrazy** [comment]
Had to purge node_modules and do npm install again.  Now works.

Maybe we can include some of this in the image in the future

**Comment by leefaus** [comment]
@geekgonecrazy 

I have some notes I need to add to the Hubot documentation around how to build without requiring a Hubot dependency.  That will make it easier for deployments too.

**Comment by geekgonecrazy** [comment]
@leefaus sounds good.  No fun writing documentation, but sure is helpful :+1:

**Pull request merged**
