### PR TITLE
feat: handle livechat message

### PR DESCRIPTION
**Pull request by gugahoa**
Hello, everyone,
In this PR there's the basic to receive livechat message without the need to mention the bot.

How to use (for now):
- Set env var RESPOND_TO_LIVECHAT to true
- Add the bot as the only agent
- Send a command (e.g: ping)

Note: It's my first contribution, so any comment is more than welcome! Also, I didn't find any contributing guide, so call me out if I miss something! :^)

### CODE REVIEW

**Comment by JigSawFr** [comment]
Great, it could be great to be able to assign first bot and have a method to transfer to a real live agent.
The process could be:

- Guest start a conversation on live chat
- After sending first message, the bot is assigned to room
- We want to transfer guest to a real live agent available (_you are able to transfer on rocket chat GUI_) after asking user or by an automate process.
- A real agent is transferred.

Good luck for your work :)

**Comment by gugahoa** [comment]
@JigSawFr https://github.com/RocketChat/Rocket.Chat/pull/7136 With this, the first agent can be a bot. :^)
As for transferring, it's the next todo on the list!

**Comment by JigSawFr** [comment]
Love it !

**Comment by geekgonecrazy** [comment]
These changes on their own look good.  I know a couple of guys on the team have done some livechat stuff with hubot some how.  Going to take a peak and see if we can combine the two.

**Comment by geekgonecrazy** [comment]
Ok I think I got it now.  

So the team is actually making use of the hear listener in hubot.  The bot is added as an agent in the queue.  When its the only one available its taking all of the messages.  

This code seems to then allow the bot to respond to messages that it is directly mentioned.  So something like `bot what is the weather?` would then be handled by the bot.

So for livechat messages it self this PR is not required.  But... it will allow mentions to be handled by the bot.

**Comment by geekgonecrazy** [comment]
@gugahoa could you add this option to the readme and i'll go ahead and merge? 

Btw thanks for the contribution!

**Pull request merged**
