### PR TITLE
Allow passing in external script dependencies via an environment variable

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Alright so need to add documentation for this.  But here's what i've got.

Four new environment variables:
* EXTERNAL_SCRIPTS
* DEV
* BOT_OWNER
* BOT_DESC

EXTERNAL_SCRIPTS can be a comma separated list. Automatically set to:
`hubot-diagnostics,hubot-help,hubot-google-images,hubot-google-translate,hubot-pugme,hubot-maps,hubot-rules,hubot-shipit` so this is not required.

DEV is automatically set to false.  But if set to true it will compile coffeescript files in `/home/hubot/node_modules/hubot-rocketchat/src/`

Couple of examples:

No Dev:  
```
docker run -it --link rocketchat:rocketchat -e ROCKETCHAT_URL=rocketchat -e ROCKETCHAT_ROOM=GENERAL -e ROCKETCHAT_USER=bot -e ROCKETCHAT_PASSWORD=bot -e BOT_NAME=bot -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help geekgonecrazy/rocketbot
```
Dev:
```
docker run -it --link rocketchat:rocketchat -e ROCKETCHAT_URL=rocketchat -e ROCKETCHAT_ROOM=GENERAL -e ROCKETCHAT_USER=bot -e ROCKETCHAT_PASSWORD=bot -e BOT_NAME=bot -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help -e DEV=true -v $PWD:/home/hubot/node_modules/hubot-rocketchat geekgonecrazy/rocketbot
```

@Sing-Li / @leefaus / @engelgabriel your input on this would also be awesome.

Also maybe we could setup an image on the rocketchat name that would hit the docker webhook to build any time a commit was made here?

Like rocketchat/rocketbot ?  Just an idea.  :)

### CODE REVIEW

**Comment by Sing-Li** [comment]
LGTM !

Even works !!  ;-)

Yes, :+1:  for the workflow :   

`github-push-webhook ->  service that check if the Dockerfile is the one being modified  -> docker-automated-build-webhook `

Also :+1: for the long overdue `rocketchat/hubot`   automated build image.

Very elegant solution for both dev and deployment environments. Kudos.

 I have only three reservations:

* a docker noob might not understand the myriad of env options available and how they interact to control the final container ... this is mainly a documentation problem; but we also need to get the 'minimal must-set variables' right, so the most typical usage appears to be simple/easy
* the guru-parsed options syntax blowing up for our Windows users - a bridge that we'll cross when they care enough to post issues
* seven pm at a restaurant down the street

**Comment by geekgonecrazy** [comment]
@Sing-Li i'd hope it works!  :smile: 

Would we actually care if it was just the dockerfile modified?  Because if a change is made to any part of this library we'd want the hubot-rocketchat dependency updated that is inside the image.

Your reservations:
* I agree this need boiled down to what is required to make this work.  I think we can boil this down even further.
* This is where my little javascript inline i'd want to swap out for a simple little npm module.  One with checks and etc.  I'll add that to my todo list.  :)
* :+1: good food?

**Comment by geekgonecrazy** [comment]
Going to go ahead an merge this.  Any objections?

**Comment by leefaus** [comment]
Let's merge.  Tested last night and everything was good to go.  Sorry for the late notice, been a crazy morning.

**Comment by geekgonecrazy** [comment]
@leefaus all good!  Just remembered I hadn't merged.  Thanks!

**Pull request merged**
