### PR TITLE
Let sendMessage lookup roomid and added caching to getRoomId (#98)

### PR DESCRIPTION
**Pull request by chkal**
This patch does two things:

* `RocketChatDriver.sendMessage()` now uses `getRoomId` to resolve the id of the requested room
* `RocketChatDriver.getRoomId()` uses a LRU cache to reduce the number of calls to the server

I tested the patch and it looks good. The "max age" setting for the cache should be configurable, but I guess this should be done in a later PR.

### CODE REVIEW

**Comment by chkal** [comment]
Please let me know if there is anything I can improve. I'm not very familiar with CoffeeScript, so the code style may not be perfect. :)

**Comment by geekgonecrazy** [comment]
Now that I think about it... Its probably safe to bump that up.  Its usually at least 20 seconds between messages on our demo server.  So almost every request would have to go back and check.

Maybe we can bump this up to like 5 minutes?

Also maybe as an easy fix to make it configurable do something like:
```
_maxAge = process.env.CACHE_AGE || 300;
_roomIdCache = LRU( max: 10, maxAge: 1000 * _maxAge )
```

So what ever is set in the environment variable CACHE_AGE or 300 seconds (5 minutes) if nothing.

@RocketChat/core thoughts?

**Comment by Sing-Li** [comment]
Wow.  Great work!    I'd suggest adding `@logger.debug 'cache hit ' + details`  (and for cache miss)  for those who need to tune for their particular use-case.     Awesome :+1:

**Comment by chkal** [comment]
Ok, I just changed the following aspects:

* The cache size and max-age are now configurable. The description for the corresponding environment variables has been added to `README.md`
* There is now a debug level log statement for cache hits. So it's easier to debug test usage.

Let me know if there is anything else I can do.

**Comment by Sing-Li** [comment]
LGTM

**Comment by geekgonecrazy** [comment]
LGTM

@chkal thanks a lot!  This is a great addition :+1:

**Pull request merged**
