### PR TITLE
Restored attachment support

### PR DESCRIPTION
**Pull request by garychapman**
Restored changes from 72bbf02d519b5dedb2b8e45e093fe2b0b23df9b3 that were lost during 92453767fb407f43bc5015db6909f1f25b5329b3

### CODE REVIEW

**Comment by Sing-Li** [comment]
LGTM

**Comment by geekgonecrazy** [comment]
lgtm thanks for adding that back.

**Comment by garychapman** [comment]
Does someone want to merge this?

**Comment by geekgonecrazy** [comment]
@garychapman on it today.  :smile: was out of town.

**Pull request merged**
