### PR TITLE
Direct Message functionality

### PR DESCRIPTION
**Pull request by NioTeX**
Script for hubot to respond with a Direct Message to a user who typed a command on a public-channel. ( Good to keep chaos out of the main channels, and this way new scripts can be created that give the user private information )
This allows hubot scripts to use something like this:

```coffee
robot.respond /DM me/i, (res) ->
    res.sendDirect "This is a DM"
```
NOTE: currently you can use `sendDirect` and `sendPrivate`, couldn't decide on a name.
* sendPrivate is used in the [hubot irc adapter](https://github.com/nandub/hubot-irc/pull/118/files)
* sendDirect is more in-line with the RocketChat 'DM' naming convention

most adapters have not implemented something like this because you can use this in them:
```coffee
robot.send {room: message.envelope.user.name}, message
```
This can not be used in RocketChat because DM channel IDs are created by concatenating the 2 user IDs, so we actually need to ask for the Room ID. ( the method also creates the channel if it didn't exist till now )

Any improvements are welcomed.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@NioTeX thanks for the PR!  

We just had a roomId cache added in by another contributor in #99.  Would you have the time to adjust this to make use of the cache?

**Comment by NioTeX** [comment]
yeah sure @geekgonecrazy, I'll add cache support in a few hours.

**Comment by NioTeX** [comment]
Caching functionality implemented.
Anything else you guys think can be useful?
@geekgonecrazy @Sing-Li

**Comment by geekgonecrazy** [comment]
@NioTeX :+1: 

LGTM

**Comment by Sing-Li** [comment]
LGTM. Thx!  :+1:

**Comment by cbrummitt** [comment]
I'm finding that `sendDirect` and `sendPrivate` don't work. When I test @NioTeX's `DM me` command locally, I get 

`ERROR TypeError: res.sendDirect is not a function
TypeError: res.sendDirect is not a function`

I'm not sure what version of the Rocket.Chat adapter I'm using, but I checked that my (May 30, 2016) version does have `sendPrivate` and `sendDirect` in the source code. I get the same error when I change an (otherwise working) `res.send` command to `res.sendPrivate`. 

Any ideas what's going wrong on my end? Thanks!

**Comment by Sing-Li** [comment]
You really need release  0.1.4  for things to work properly, not anything earlier or later....

See

https://github.com/RocketChat/hubot-rocketchat/releases

**Comment by cbrummitt** [comment]
I ran `npm update` and verified that I've updated the local copy of hubot-rocketchat from 0.1.2 to 0.1.4. But I still get the same error: `TypeError: res.sendDirect is not a function`. 😕

**Comment by geekgonecrazy** [comment]
@cbrummitt looks like a permission issue.  Check the role your bot has been assigned and see if it has the: `create-d` permission

**Comment by cbrummitt** [comment]
Thanks @geekgonecrazy. Enabling the `create-d` permission for the `bot

**Pull request merged**
