### PR TITLE
Cleanup callback pyramid and log full error.

### PR DESCRIPTION
**Pull request by STRML**
Compare with [this link](https://github.com/RocketChat/hubot-rocketchat/pull/86/files?w=1) to eliminate whitespace changes.

This fixes the unreadable code as seen below:

screen shot 2015-12-21 at 9 56 59 am

This also stringifies errors when reporting them. This helped with a frustrating issue where Rocket.Chat was refusing my password due to a special character, but hubot was only logging `[object Object]`.

Tested working on a live hubot instance.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@STRML Thanks for the PR.  I notice you switched from tab to space in the editorconfig file.  We're attempting to standardize all of our projects. 

If possible could this be switched back to be consistant? If not I can merge and fix these.

Appreciate you taking the time to open the PR.

**Comment by STRML** [comment]
Yeah that's fine. Spaces are generally better imo since github
(unfortunately) renders tabs as 8 spaces instead of 4, making the pyramid
effect even worse. So I use 2 spaces in most of my projects.

**Comment by STRML** [comment]
:shipit:

**Comment by Sing-Li** [comment]
@STRML - *Thank you* for the refactor!!

Due to inherent complexity, it is close to impossible to visually verify the correctness of the refactor.  

We did the best we can, and will merge the PR.   Our community BOT power-user @sinteur has graciously agreed to test the refactored code on his highly stressed configurations. 

Please stand-by to support the refactor - should problem arises.  Thanks again.

**Comment by Sing-Li** [comment]
@sinteur  and @STRML - the npm module has been updated to 0.0.23 for testing of the refactored code. 

Please test when you get a chance, and report any issues found.  Thanks again.

**Pull request merged**
