### PR TITLE
Fixing improper use of .then -- also some clean-up

### PR DESCRIPTION
**Pull request by Theaxiom**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
can you explain how this was an improper use of .then ?

**Comment by Theaxiom** [comment]
I'm new to asteroid, coffeescript, meteor and rocket.chat -- however, I changed the error message from err.reason to err and received this: [Wed Sep 23 2015 11:59:36 GMT-0700 (PDT)] ERROR Unable to Login. Reason: TypeError: room.then is not a function

I could be wrong, but someone would need to at least re-visit that code and fix it so it works out of the box. I am not the expert to make it work, I just removed it to get it working.

**Comment by Theaxiom** [comment]
I also noticed npm is not updated with the lastest version.

**Comment by geekgonecrazy** [comment]
@Theaxiom i'll look into this.  We for sure don't want to just remove the then / catch on login.  We need to handle an unsuccessful login.

**Comment by Theaxiom** [comment]
The exception handling is still there for login.... honestly the handler that was there seemed superfluous

**Comment by Theaxiom** [comment]
This is what I removed, and it seems absolutely not necessary: https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L42

It is also breaking the code.

**Comment by Theaxiom** [comment]
I also removed this: https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L63

**Comment by Theaxiom** [comment]
I was under the impression you can only chain functions...

**Comment by graywolf336** [comment]
If the `then` from `@chatdriver.joinRoom userid, RocketChatUser, room` is saying `[Wed Sep 23 2015 11:59:36 GMT-0700 (PDT)] ERROR Unable to Login. Reason: TypeError: room.then is not a function` then it seems the promise being returned isn't correct and that's a bigger problem than just removing the `then`?

**Comment by geekgonecrazy** [comment]
Ah sorry.  I meant for room join.

Mainly these are added for the people that are having issues and need to know why its not working.  We have many people asking why their bot isn't working.  So if we have it log out specifically that its a login error or a room join error.  Then we know exactly where it is.  I agree it is maybe super verbose.  But its useful to be able to tell exactly where the error is.

Promises aren't only used for chaining functions.  They are used a lot as a sort of try / catch sort of deal.  You can send off a request to do something then have a call back for if an error or then if success.

Of course that lets you chain them too.

if you simply put: `@chatdriver.joinRoom(userid, RocketChatUser, room)` that will fix it.  

Because yes room doesn't return a promise.  :) because joinRoom is the one we want the promise from.  Just a little coffeescript weirdness.  

If you want to give that a try, i'd much prefer keep handling of errors there for joinRoom

**Comment by Theaxiom** [comment]
Like I said, I didn't have enough experience to fix this. And yes, I was having an issue that my bot wouldn't join my other rooms, and I had to go through and figure it out. The changes I made helped to lead me in the right direction. Thanks for looking into it.

**Comment by geekgonecrazy** [comment]
@Theaxiom did you want to give changing that a go?  If not i'll gladly fix it and get npm to update

**Comment by Theaxiom** [comment]
@geekgonecrazy Please go for it. :) Thanks!

**Comment by geekgonecrazy** [comment]
18bd7c9be0

Also should update on npm

**Comment by Theaxiom** [comment]
Thank you. :)

**Comment by Theaxiom** [comment]
How long does it take to update? https://www.npmjs.com/package/hubot-rocketchat

**Comment by geekgonecrazy** [comment]
@Theaxiom its usually instant... Trying to figure that out now.  Not sure what's going on

**Comment by geekgonecrazy** [comment]
@Theaxiom should be updated now.  The website seems to be taking a while.  If doing npm install doesn't you can do:

`npm install hubot-rocketchat@0.0.9`

**Comment by Theaxiom** [comment]
Thank you. :)

**Pull request closed without merging**
