### PR TITLE
Add support for joining rooms by name (fixes #5)

### LINKED ISSUE #5: Implement join room(s) by room name(s)
Enable users to specify a room (or an array of rooms) by name. Currently implementation requires room IDs - which are no longer easy to find.

### PR DESCRIPTION
**Pull request by Shelnutt2**
This requires https://github.com/RocketChat/Rocket.Chat/pull/1104

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@Shelnutt2 thanks for the PR.  Will make sure we get things merged in the main project then take a look at this.  :+1:

**Comment by Shelnutt2** [comment]
@geekgonecrazy The PR on the main project was merged, any chance you guys can take a look at this now?

**Comment by geekgonecrazy** [comment]
@Shelnutt2 I apologize, forgot to subscribe to the other so I would know it was finished.  

I have one concern with this.  Looks like its now room name or nothing.  If people already have this configured for roomid then their bot breaks right?

**Comment by Shelnutt2** [comment]
@geekgonecrazy It supports both, as the server side function will return the room ID and accepts either a name or an ID. So existing deployments should not be effected.

You can see this here: https://github.com/RocketChat/Rocket.Chat/commit/610284452317c0d9e5eb23f4b32a592a2fd36094

**Comment by geekgonecrazy** [comment]
I over looked that.  :)  LGTM

**Pull request merged**
