### PR TITLE
Allow hubot to emote

### PR DESCRIPTION
**Pull request by paul-bjorkstrand**

### CODE REVIEW

**Comment by paul-bjorkstrand** [comment]
Let's give hubot some emotion in Rocket.Chat channels!

**Comment by geekgonecrazy** [comment]
Hey thanks for the contribution.  I do have a bit of worry on the name.  Is emote used for /me typically?  To me emote would mean more of emoji or something

**Comment by paul-bjorkstrand** [comment]
Emote is the built-in `/me`-like message. See https://github.com/github/hubot/blob/master/src/adapters/shell.coffee#L23 for the Shell one. The `*` at the beginning of that is the raw irc-derived `/me` trigger.

**Comment by paul-bjorkstrand** [comment]
Also, in the IRC version: https://github.com/nandub/hubot-irc/blob/master/src/irc.coffee#L45 you can see it uses the irc `notice` or `action` message types.

**Comment by geekgonecrazy** [comment]
Ok that works for me!  I just wanted to make sure it was going to be a known or expected behaviour.  :+1: 

Thanks for the links :)

**Comment by paul-bjorkstrand** [comment]
Thanks! Just out of curiosity, do you have a specific release (& npm push) cadence for this adapter? Currently, I am using locally modified version for testing purposes. I mainly ask because the last release was in October 2016.

**Comment by geekgonecrazy** [comment]
no real cadence.  Just when we get new features landing and enough for a release.  I've gone ahead and cut a new one :+1:

**Pull request merged**
