### PR TITLE
Add attachment support

### PR DESCRIPTION
**Pull request by ngenerio**
This adds the attachment support #139. @geekgonecrazy @timkinnane. This [file](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-file-upload/server/methods/sendFileMessage.js) should probably help clear things out. Thanks.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@ngenerio Much better! :smile: I need to get a couple of versioning things worked out and i'll get your changes in. 

Thanks again!

**Comment by ngenerio** [comment]
:+1

**Comment by Sing-Li** [comment]
LGTM.  It would be gr8 to get this merged soon. And get HEAD back to a workable version. Thx.

**Comment by geekgonecrazy** [comment]
@ngenerio ok I fixed the main branch.  Is it possible you could re-open #144 ?

**Comment by ngenerio** [comment]
@geekgonecrazy I had an issue with some merge conflicts whiles working. I had to delete the repo, fork and make the changes again. The only way will be to open another pull request.

**Comment by geekgonecrazy** [comment]
@ngenerio hate to ask... But would you mind doing that?  I rolled the branch back to v0.1.4 to get rid of the code causing everyone issues. 

If its too much trouble let me know and I'll try and cherry pick your commit out and open a new PR.  😄

**Comment by ngenerio** [comment]
@geekgonecrazy Done. Pull request: #148 .

**Comment by geekgonecrazy** [comment]
Closing in favor of #148

**Comment by ngenerio** [comment]
I guess this pull request can be closed.

**Comment by geekgonecrazy** [comment]
@ngenerio v1.0.0 and v1.0.1 were released pre-maturely. Your code is in, and will be in all future releases.  Thanks again 👍

**Comment by ngenerio** [comment]
:+1: Sounds great. You did a roll back to v1.0.4.

**Pull request closed without merging**
